title: Simple website example

markdown: kramdown

# kramdown:
#   parse_block_html: true

plugins:
  - jekyll-feed

feed:
  path: atom.xml

sass:
  style: compressed

show_excerpts: true

include: 
  - _pages
  - .htaccess

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock