name: CI

on:
  push:
    branches:
      - dist

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy to branch
      uses: danbraj/jekyll-build-action@master
      with:
        greet: Test
      env:
        TOKEN: ${{ secrets.TOKEN }}
        DEPLOY_BRANCH: deployment
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@master
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        LOCAL_DIR: _site