name: CI

on:
  push:
    branches:
      - dist

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Deploy website
      uses: danbraj/jekyll-build-action@master
      with:
        greet: Dan
      env:
        DEPLOY_BRANCH: deployment
