name: CI

on:
  push:
    branches:
      - dist

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy to branch
      uses: danbraj/jekyll-build-action@master
      with:
        greet: Test
      env:
        TOKEN: ${{ secrets.TOKEN }}
        DEPLOY_BRANCH: deployment
    - name: Deploy to FTP
      uses: sebastianpopp/ftp-action@master
      with:
        host: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "_site"